### ISSUE TITLE
add new booting option via OT SPI

### ISSUE THREAD

**Issue by davideschiavone** [esl-epfl/x-heep#69]

**Comment by benoitdenkinger** [comment]
In progress in #94

**Comment by benoitdenkinger** [comment]
Booting using the Opentitan SPI (SPI host) works for the hello world example, but I have to manually edit the hex file: replace all addresses @4... with @0...
The problem is that the code is the same than the normal one (when booting from jtag) but stored in the flash @0x00000010 because the four first words are reserved for the bootrom to know where to load code from. I don't how to generate directly from the linker script the correct addresses.

**Comment by benoitdenkinger** [comment]
This problem is solved. The --adjust-vma option was missing when creating the hex file.
